### ISSUE TITLE
Atributo hidden aria

### ISSUE THREAD

**Issue by JoseLuisMaya** [EGCAgoraVotingAccG2/agora-gui-common#1]
En agora-gui-common/avRegistration/fields/email-field-directive/email-field-directive.html el campo hidden desde html5 no es necesario poner el valor true.

**Comment by eduardogr1984** [comment]
Gracias @JoseLuisMaya por la indicación. Tienes razón, ya he eliminado los valores "true" de las etiquetas hidden.

Además de en ese archivo, lo tenía en alguno más así que he aprovechado y he modificado también los otros. Se ha actualizado la rama "development" con esa pequeña modificación de buenas prácticas.
